name: Manual Render

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y xvfb libgbm1 libasound2 && npm install

      - name: Render
        run: xvfb-run npx remotion render Main out/video.mp4

      - name: Upload
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: video
          path: out/video.mp4